# -*- coding: utf-8 -*-
from . import browsable_object
from . import account_journal,hr_leave,hr_vacation,hr_cesantias,hr_prima,hr_contrato,hr_payroll,hr_payroll_other,hr_payroll_account_move
from . import res_config_settings,hr_loans,hr_overtime,hr_concepts_deduction_retention,hr_calculation_rtefte_ordinary,hr_payroll_flat_file,lavish_payroll_flat_file_backup
from . import hr_payroll_report_lavish,hr_voucher_sending,hr_novelties_different_concepts,hr_novelties_independents,hr_payroll_posting,hr_accumulated_payroll,hr_work_entry,hr_contract
from . import hr_electronic_payroll, hr_electronic_adjust_payroll, hr_payroll_base_values_excel, hr_accumulated_reports, hr_absence_history, hr_consolidated_reports, hr_auditing_reports
from . import hr_payslip_run_report_entity, hr_vacation_book_reports,res_partner, hr_payslip_reports_template, hr_report_absenteeism_history, hr_transfers_of_entities, hr_withholding_and_income_certificate
from . import hr_slip
