
# Generated by CodiumAI

import pytest

class TestHrPayrollSocialSecurity:

    # The method successfully retrieves annual parameters based on the year provided.
    def test_retrieve_annual_parameters(self):
        # Create a mock annual parameters record
        annual_parameters = self.env['hr.annual.parameters'].create({
            'year': 2022,
            # Add other required fields
        })
    
        # Set the year attribute of the hr_payroll_social_security instance
        self.year = 2022
    
        # Call the get_plano method
        self.get_plano()
    
        # Assert that the annual parameters are retrieved correctly
        assert self.env['hr.annual.parameters'].search([('year', '=', self.year)]) == annual_parameters

